version = 0.1
[default.deploy.parameters]
stack_name = "booking-ticket"
resolve_s3 = true
s3_prefix = "booking-ticket"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
